apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
  namespace: default # 네임스페이스 추가
spec:
  selector:
    app: my-backend
  ports:
    - protocol: TCP
      port: 80 # 외부에 노출할 포트
      targetPort: 8000 # 컨테이너 내부의 포트
  type: LoadBalancer # 외부에서 접근 가능하게 하려면 LoadBalancer 타입으로 설정
